package ClassesHib;
// Generated 17/11/2016 16:01:29 by Hibernate Tools 4.3.1



/**
 * Assentoscomprados generated by hbm2java
 */
public class Assentoscomprados  implements java.io.Serializable {


     private AssentoscompradosId id;
     private double vrpag;

    public Assentoscomprados() {
    }

    public Assentoscomprados(AssentoscompradosId id, double vrpag) {
       this.id = id;
       this.vrpag = vrpag;
    }
   
    public AssentoscompradosId getId() {
        return this.id;
    }
    
    public void setId(AssentoscompradosId id) {
        this.id = id;
    }
    public double getVrpag() {
        return this.vrpag;
    }
    
    public void setVrpag(double vrpag) {
        this.vrpag = vrpag;
    }




}


