package ClassesHib;
// Generated 17/11/2016 16:01:29 by Hibernate Tools 4.3.1



/**
 * Passageiros generated by hbm2java
 */
public class Passageiros  implements java.io.Serializable {


     private String idpas;
     private String nmpas;
     private String snpas;
     private String idpaispas;
     private String telpas;
     private String endpas;
     private int iddpas;
     private String cpfpas;
     private String pstpas;

    public Passageiros() {
    }

	
    public Passageiros(String idpas, String nmpas, String snpas, String idpaispas, String telpas, String endpas, int iddpas) {
        this.idpas = idpas;
        this.nmpas = nmpas;
        this.snpas = snpas;
        this.idpaispas = idpaispas;
        this.telpas = telpas;
        this.endpas = endpas;
        this.iddpas = iddpas;
    }
    public Passageiros(String idpas, String nmpas, String snpas, String idpaispas, String telpas, String endpas, int iddpas, String cpfpas, String pstpas) {
       this.idpas = idpas;
       this.nmpas = nmpas;
       this.snpas = snpas;
       this.idpaispas = idpaispas;
       this.telpas = telpas;
       this.endpas = endpas;
       this.iddpas = iddpas;
       this.cpfpas = cpfpas;
       this.pstpas = pstpas;
    }
   
    public String getIdpas() {
        return this.idpas;
    }
    
    public void setIdpas(String idpas) {
        this.idpas = idpas;
    }
    public String getNmpas() {
        return this.nmpas;
    }
    
    public void setNmpas(String nmpas) {
        this.nmpas = nmpas;
    }
    public String getSnpas() {
        return this.snpas;
    }
    
    public void setSnpas(String snpas) {
        this.snpas = snpas;
    }
    public String getIdpaispas() {
        return this.idpaispas;
    }
    
    public void setIdpaispas(String idpaispas) {
        this.idpaispas = idpaispas;
    }
    public String getTelpas() {
        return this.telpas;
    }
    
    public void setTelpas(String telpas) {
        this.telpas = telpas;
    }
    public String getEndpas() {
        return this.endpas;
    }
    
    public void setEndpas(String endpas) {
        this.endpas = endpas;
    }
    public int getIddpas() {
        return this.iddpas;
    }
    
    public void setIddpas(int iddpas) {
        this.iddpas = iddpas;
    }
    public String getCpfpas() {
        return this.cpfpas;
    }
    
    public void setCpfpas(String cpfpas) {
        this.cpfpas = cpfpas;
    }
    public String getPstpas() {
        return this.pstpas;
    }
    
    public void setPstpas(String pstpas) {
        this.pstpas = pstpas;
    }




}


