package ClassesHib;
// Generated 17/11/2016 16:01:29 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Voos generated by hbm2java
 */
public class Voos  implements java.io.Serializable {


     private String idvoo;
     private String idaerpar;
     private String idaerche;
     private Date hrpar;
     private Date dtpar;
     private Date hrche;
     private Date dtche;

    public Voos() {
    }

    public Voos(String idvoo, String idaerpar, String idaerche, Date hrpar, Date dtpar, Date hrche, Date dtche) {
       this.idvoo = idvoo;
       this.idaerpar = idaerpar;
       this.idaerche = idaerche;
       this.hrpar = hrpar;
       this.dtpar = dtpar;
       this.hrche = hrche;
       this.dtche = dtche;
    }
   
    public String getIdvoo() {
        return this.idvoo;
    }
    
    public void setIdvoo(String idvoo) {
        this.idvoo = idvoo;
    }
    public String getIdaerpar() {
        return this.idaerpar;
    }
    
    public void setIdaerpar(String idaerpar) {
        this.idaerpar = idaerpar;
    }
    public String getIdaerche() {
        return this.idaerche;
    }
    
    public void setIdaerche(String idaerche) {
        this.idaerche = idaerche;
    }
    public Date getHrpar() {
        return this.hrpar;
    }
    
    public void setHrpar(Date hrpar) {
        this.hrpar = hrpar;
    }
    public Date getDtpar() {
        return this.dtpar;
    }
    
    public void setDtpar(Date dtpar) {
        this.dtpar = dtpar;
    }
    public Date getHrche() {
        return this.hrche;
    }
    
    public void setHrche(Date hrche) {
        this.hrche = hrche;
    }
    public Date getDtche() {
        return this.dtche;
    }
    
    public void setDtche(Date dtche) {
        this.dtche = dtche;
    }




}


