package Classes;
// Generated 17/11/2016 16:01:29 by Hibernate Tools 4.3.1



/**
 * Assentos generated by hbm2java
 */
public class Assentos  implements java.io.Serializable {


     private String idass;
     private String idvoo;
     private String idpas;
     private String idcla;
     private String nmass;

    public Assentos() {
    }

    public Assentos(String idass, String idvoo, String idpas, String idcla, String nmass) {
       this.idass = idass;
       this.idvoo = idvoo;
       this.idpas = idpas;
       this.idcla = idcla;
       this.nmass = nmass;
    }
   
    public String getIdass() {
        return this.idass;
    }
    
    public void setIdass(String idass) {
        this.idass = idass;
    }
    public String getIdvoo() {
        return this.idvoo;
    }
    
    public void setIdvoo(String idvoo) {
        this.idvoo = idvoo;
    }
    public String getIdpas() {
        return this.idpas;
    }
    
    public void setIdpas(String idpas) {
        this.idpas = idpas;
    }
    public String getIdcla() {
        return this.idcla;
    }
    
    public void setIdcla(String idcla) {
        this.idcla = idcla;
    }
    public String getNmass() {
        return this.nmass;
    }
    
    public void setNmass(String nmass) {
        this.nmass = nmass;
    }




}


