package Classes;
// Generated 17/11/2016 16:01:29 by Hibernate Tools 4.3.1



/**
 * AssentoscompradosId generated by hbm2java
 */
public class AssentoscompradosId  implements java.io.Serializable {


     private String idres;
     private String idass;
     private String idvoo;

    public AssentoscompradosId() {
    }

    public AssentoscompradosId(String idres, String idass, String idvoo) {
       this.idres = idres;
       this.idass = idass;
       this.idvoo = idvoo;
    }
   
    public String getIdres() {
        return this.idres;
    }
    
    public void setIdres(String idres) {
        this.idres = idres;
    }
    public String getIdass() {
        return this.idass;
    }
    
    public void setIdass(String idass) {
        this.idass = idass;
    }
    public String getIdvoo() {
        return this.idvoo;
    }
    
    public void setIdvoo(String idvoo) {
        this.idvoo = idvoo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AssentoscompradosId) ) return false;
		 AssentoscompradosId castOther = ( AssentoscompradosId ) other; 
         
		 return ( (this.getIdres()==castOther.getIdres()) || ( this.getIdres()!=null && castOther.getIdres()!=null && this.getIdres().equals(castOther.getIdres()) ) )
 && ( (this.getIdass()==castOther.getIdass()) || ( this.getIdass()!=null && castOther.getIdass()!=null && this.getIdass().equals(castOther.getIdass()) ) )
 && ( (this.getIdvoo()==castOther.getIdvoo()) || ( this.getIdvoo()!=null && castOther.getIdvoo()!=null && this.getIdvoo().equals(castOther.getIdvoo()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdres() == null ? 0 : this.getIdres().hashCode() );
         result = 37 * result + ( getIdass() == null ? 0 : this.getIdass().hashCode() );
         result = 37 * result + ( getIdvoo() == null ? 0 : this.getIdvoo().hashCode() );
         return result;
   }   


}


