package Classes;
// Generated 17/11/2016 16:01:29 by Hibernate Tools 4.3.1



/**
 * Cidades generated by hbm2java
 */
public class Cidades  implements java.io.Serializable {


     private String idcid;
     private String nmcid;

    public Cidades() {
    }

    public Cidades(String idcid, String nmcid) {
       this.idcid = idcid;
       this.nmcid = nmcid;
    }
   
    public String getIdcid() {
        return this.idcid;
    }
    
    public void setIdcid(String idcid) {
        this.idcid = idcid;
    }
    public String getNmcid() {
        return this.nmcid;
    }
    
    public void setNmcid(String nmcid) {
        this.nmcid = nmcid;
    }




}


