package Classes;
// Generated 17/11/2016 16:01:29 by Hibernate Tools 4.3.1



/**
 * Paises generated by hbm2java
 */
public class Paises  implements java.io.Serializable {


     private String idpais;
     private String nmpais;

    public Paises() {
    }

    public Paises(String idpais, String nmpais) {
       this.idpais = idpais;
       this.nmpais = nmpais;
    }
   
    public String getIdpais() {
        return this.idpais;
    }
    
    public void setIdpais(String idpais) {
        this.idpais = idpais;
    }
    public String getNmpais() {
        return this.nmpais;
    }
    
    public void setNmpais(String nmpais) {
        this.nmpais = nmpais;
    }




}


