package Classes;
// Generated 17/11/2016 16:01:29 by Hibernate Tools 4.3.1



/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private String idusu;
     private String emailusu;
     private String nmusu;
     private String senhausu;

    public Usuarios() {
    }

	
    public Usuarios(String idusu, String nmusu, String senhausu) {
        this.idusu = idusu;
        this.nmusu = nmusu;
        this.senhausu = senhausu;
    }
    public Usuarios(String idusu, String emailusu, String nmusu, String senhausu) {
       this.idusu = idusu;
       this.emailusu = emailusu;
       this.nmusu = nmusu;
       this.senhausu = senhausu;
    }
   
    public String getIdusu() {
        return this.idusu;
    }
    
    public void setIdusu(String idusu) {
        this.idusu = idusu;
    }
    public String getEmailusu() {
        return this.emailusu;
    }
    
    public void setEmailusu(String emailusu) {
        this.emailusu = emailusu;
    }
    public String getNmusu() {
        return this.nmusu;
    }
    
    public void setNmusu(String nmusu) {
        this.nmusu = nmusu;
    }
    public String getSenhausu() {
        return this.senhausu;
    }
    
    public void setSenhausu(String senhausu) {
        this.senhausu = senhausu;
    }




}


